// Tamil Nadu Districts to Constituencies Mapping Config

const DISTRICTS_MAPPING = {
    "Ariyalur": ["Ariyalur", "Jayankondam"],
    "Chengalpattu": ["Chengalpattu", "Tambaram", "Pallavaram", "Madhurantakam", "Cheyyur", "Tiruporur", "Sholinganallur"],
    "Chennai": ["Dr. Radhakrishnan Nagar", "Perambur", "Kolathur", "Villivakkam", "Thiru-Vi-Ka-Nagar", "Egmore", "Royapuram", "Harbour", "Chepauk-Triplicane", "Thousand Lights", "Anna Nagar", "Virugambakkam", "Saidapet", "T. Nagar", "Mylapore", "Velachery"],
    "Coimbatore": ["Coimbatore North", "Coimbatore South", "Kavundampalayam", "Singanallur", "Sulur", "Thondamuthur", "Kinathukadavu", "Pollachi", "Valparai", "Mettupalayam"],
    "Cuddalore": ["Cuddalore", "Neyveli", "Panruti", "Chidambaram", "Vriddhachalam", "Kurinjipadi", "Bhuvanagiri", "Tittakudi"],
    "Dharmapuri": ["Dharmapuri", "Pennagaram", "Palacode", "Harur", "Pappireddipatti"],
    "Dindigul": ["Dindigul", "Palani", "Oddanchatram", "Athoor", "Nilakottai", "Natham", "Vedasandur", "Kodaikanal"],
    "Erode": ["Erode East", "Erode West", "Modakkurichi", "Perundurai", "Bhavani", "Anthiyur", "Gobichettipalayam", "Bhavanisagar"],
    "Kallakurichi": ["Kallakurichi", "Sankarapuram", "Rishivandiyam", "Ulundurpet"],
    "Kanchipuram": ["Kanchipuram", "Sriperumbudur", "Uthiramerur", "Alandur"],
    "Kanyakumari": ["Nagercoil", "Kanyakumari", "Colachel", "Padmanabhapuram", "Vilavancode", "Killiyoor"],
    "Karur": ["Karur", "Aravakurichi", "Krishnarayapuram", "Kulithalai"],
    "Krishnagiri": ["Krishnagiri", "Hosur", "Thalli", "Burgur", "Uthangarai", "Vepanapalli"],
    "Madurai": ["Madurai East", "Madurai West", "Madurai North", "Madurai South", "Melur", "Thiruparankundram", "Sholavandan", "Usilampatti", "Tirumangalam", "Madurai Central"],
    "Mayiladuthurai": ["Mayiladuthurai", "Sirkazhi", "Poompuhar"],
    "Nagapattinam": ["Nagapattinam", "Kilvelur", "Vedaranyam"],
    "Namakkal": ["Namakkal", "Rasipuram", "Senthamangalam", "Tiruchengodu", "Kumarapalayam", "Paramathi-Velur"],
    "Nilgiris": ["Ootacamund", "Coonoor", "Gudalur"],
    "Perambalur": ["Perambalur", "Kunnam"],
    "Pudukkottai": ["Pudukkottai", "Alangudi", "Aranthangi", "Gandharvakottai", "Viralimalai", "Thirumayam"],
    "Ramanathapuram": ["Ramanathapuram", "Paramakudi", "Tiruvadanai", "Mudukulathur"],
    "Ranipet": ["Ranipet", "Arcot", "Arakkonam", "Sholinghur"],
    "Salem": ["Salem North", "Salem South", "Salem West", "Edappadi", "Mettur", "Omalur", "Yercaud", "Attur", "Gangavalli", "Veerapandi", "Sankari"],
    "Sivagangai": ["Sivagangai", "Karaikudi", "Tiruppattur", "Manamadurai"],
    "Tenkasi": ["Tenkasi", "Kadayanallur", "Sankarankovil", "Vasudevanallur", "Alangulam"],
    "Thanjavur": ["Thanjavur", "Kumbakonam", "Pattukkottai", "Orathanadu", "Thiruvaiyaru", "Papanasam", "Peravurani", "Gandarvakottai"],
    "Theni": ["Theni", "Bodinayakanur", "Cumbum", "Periyakulam", "Andipatti"],
    "Thoothukudi": ["Thoothukudi", "Kovilpatti", "Tiruchendur", "Srivaikuntam", "Ottapidaram", "Vilathikulam"],
    "Tiruchirappalli": ["Tiruchirappalli East", "Tiruchirappalli West", "Srirangam", "Manachanallur", "Lalgudi", "Musiri", "Thuraiyur", "Manapparai", "Tiruverumbur"],
    "Tirunelveli": ["Tirunelveli", "Ambasamudram", "Palayamkottai", "Nanguneri", "Radhapuram"],
    "Tirupathur": ["Tirupathur", "Vaniyambadi", "Ambur"],
    "Tiruppur": ["Tiruppur North", "Tiruppur South", "Palladam", "Dharapuram", "Kangayam", "Udumalaipettai", "Madathukulam", "Avinashi"],
    "Tiruvallur": ["Tiruvallur", "Avadi", "Poonamallee", "Ambattur", "Maduravoyal", "Tiruttani", "Gummidipoondi", "Ponneri"],
    "Tiruvannamalai": ["Tiruvannamalai", "Arani", "Chengam", "Polur", "Vandavasi", "Cheyyar", "Kalasapakkam"],
    "Tiruvarur": ["Tiruvarur", "Mannargudi", "Thiruthuraipoondi", "Nannilam"],
    "Vellore": ["Vellore", "Katpadi", "Anaikattu", "Gudiyattam", "K.V. Kuppam"],
    "Viluppuram": ["Viluppuram", "Tindivanam", "Vikravandi", "Gingee", "Mailam", "Vanur"],
    "Virudhunagar": ["Virudhunagar", "Sivakasi", "Aruppukkottai", "Rajapalayam", "Srivilliputhur", "Sattur", "Tiruchuli"]
};

module.exports = DISTRICTS_MAPPING;
